#!/usr/bin/env php
<?php
/*
 * Sakura Mahou
 * Get it, because Sakura is a magical girl in that one anime?
 * Kill me.
 */

// Declare Namespace
namespace Sakura;

// Uses
use Sakura\Console\Application;
use GetOptionKit\Exception\InvalidOptionException;

// Include components
require_once 'sakura.php';

// Create an instance
$console = new Application;

// Attempt to run
try {
    $console->run($argv);
} catch (InvalidOptionException $e) {
    die($e->getMessage());
}
